# Generated by Django 3.1.4 on 2021-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0002_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chosenmaterials',
            old_name='req',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='chosenservices',
            old_name='req',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='executor',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='req',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='paymentorder',
            old_name='req',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='final_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='req_date',
            new_name='request_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tel',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='workgroup',
            old_name='req',
            new_name='request',
        ),
        migrations.RemoveField(
            model_name='client',
            name='legal_entity',
        ),
        migrations.RemoveField(
            model_name='materialspl',
            name='description',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
