# Generated by Django 3.1.4 on 2021-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_agency', '0003_auto_20210312_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ad', 'Администратор'), ('ma', 'Менеджер'), ('ac', 'Бухгалтер')], max_length=20),
        ),
    ]
